### ISSUE TITLE
use offline stt for "jasper" keyword and online sst for the rest

### ISSUE THREAD

**Issue by mkristian** [jasperproject/jasper-client#373] opened 2015-10-01 08:07 UTC
I really feel creepy letting google or anyone else listing what is said in the room. but as sphinx is really bad with my experience and others  #362 I thought things can be improved a bit.

having two stt engine configured. one which is used to trigger "jasper" and the other which does the heavy work. this would allow me to use sphinx for the one which listens all the time and only if I want to talk to jasper it will go online.

I did not look into the codebase if this is possible to implement. first I wanted to have some feedback on the idea and from people how have some inside to casebase.

**Comment by Holzhaus** [comment] 2015-10-01 14:51
Duplicate of #322.

**Closed by Holzhaus** 2015-10-01 14:51 UTC
Labels: duplicate

**Comment by mkristian** [comment] 2015-10-01 15:05
sweet it is already there :)
